language: generic
os: osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
sudo: required
before_install:
  - sudo apt-get update && sudo apt-get -y install build-essential make cmake libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libudev-dev libjpeg8-dev libjpeg-turbo8-dev libsndfile1-dev libopenal-dev
  - git clone https://github.com/SFML/SFML.git
  - cd SFML
  - cmake . && make && sudo make install
branches:
    only: royale
script:
  - cd meuporg-server && cmake . && make && cd ..
  - cd meuporg-client && cmake . && make && cd ..
