language: generic
os: osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsfml-dev
branches:
    only: royale
script: make
